### ISSUE TITLE
Minor conflict with LethalSnap mod

### ISSUE THREAD

**Issue by ThePhxRises** [Test-Account666/LethalCompany-ScannableTools#1] opened 2024-03-26 00:56 UTC
The Polaroid from the [LethalSnap](https://thunderstore.io/c/lethal-company/p/SweetOnion/LethalSnap/) mod already has its own scan node, but an additional one is added by this mod, causing two overlapping scan nodes of different colors to appear when scanning a polaroid.

**Comment by Test-Account666** [comment] 2024-03-26 08:31
Cannot reproduce :thinking: 

![image](https://github.com/TheBlackEntity/LethalCompany-ScannableTools/assets/36412486/4f4f048a-bad4-41b4-bf2e-332275397671)

**Comment by Test-Account666** [comment] 2024-03-26 08:40
Not even when generated normally:
![image](https://github.com/TheBlackEntity/LethalCompany-ScannableTools/assets/36412486/9e01a190-5392-4302-ba7a-21089ba25efe)

**Comment by Test-Account666** [comment] 2024-03-26 08:52
Nevermind!

I didn't notice there's a shop-bought version too.

Is fixed in 1.1.0 through a blacklist containing `polaroid` as default value

**Closed as completed by Test-Account666** 2024-03-26 08:52 UTC
